; =============================================================================
; PlatformIO – Waveshare RP2350-LCD-1.47-A
; =============================================================================
; Display : ST7789V2, 172 × 320 px
; Library : GFX Library for Arduino (moononournation)
; GUI tool: Lopaka  → https://lopaka.app
;
; All display settings are set via the TFT_* build flags below.
; =============================================================================

[platformio]
default_envs = rp2350

[env:rp2350]
platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipico2
framework = arduino
board_build.core = earlephilhower
upload_protocol = picotool
upload_flags =
    -f
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
lib_deps =
    moononournation/GFX Library for Arduino
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    miguelbalboa/MFRC522@^1.4.10
    fastled/FastLED
build_flags =
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_MISO=255
    -DTFT_CS=17
    -DTFT_DC=16
    -DTFT_RST=20
    -DTFT_BL=21
    -DRGBIO=22